# Generated by Django 3.0.1 on 2020-02-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BigIntegerField(unique=True)),
                ('news_letter', models.BooleanField(default=False)),
                ('inbox_notifications', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('search_collections', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BigIntegerField(unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
