# Generated by Django 3.0.3 on 2020-02-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_settings_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_content',
            name='owner',
            field=models.BigIntegerField(),
        ),
    ]
