# Generated by Django 3.0.3 on 2020-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200212_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_settings',
            name='profile_picture',
            field=models.ImageField(help_text='Profile Picture', null=True, upload_to='profile_img/'),
        ),
    ]
