# Generated by Django 3.0.3 on 2020-02-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_settings_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_settings',
            name='profile_picture',
            field=models.ImageField(help_text='Profile Picture', null=True, upload_to='img/profile_img/'),
        ),
    ]
